name: Critical lint codebase

on:
  push:
    branches: main
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    name: Critical lint
    steps:
    - uses: actions/checkout@v4

    - name: Lint
      uses: astral-sh/ruff-action@v1
      # with:
        # changed-files: 'true'
