name: Ruff
on:
  push:
    branches: main
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        uses: chartboost/ruff-action@v1
        with:
          args: "check"
          # changed-files: 'true'
      - name: Format
        uses: chartboost/ruff-action@v1        
        with:
          args: "format --check"
          # changed-files: 'true'